server:
  port: 80


spring:
  application:
    name: cloud-order-openfeign-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#     单机版
      defaultZone: http://eureka8761.com:8761/eureka/
#      集群版
#      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/
  instance:
      instance-id: order80
      prefer-ip-address: true

#openfeign集成了ribbon 默认连接和读取时间为1S，特殊情况在这里设置
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000



