server:
  port: 8761


eureka:
  instance:
#  单机版
    hostname: localhost
#    集群版
#    hostname: eureka8761.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是服务中心，主要职责是维护服务，不用去检索服务
    service-url: #与eureka交互的地址，查询服务和注册服务都需要依赖这个地址
#     单机版
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      集群版
#      defaultZone: http://eureka8762.com:8762/eureka/ #服务器相互注册是根据域名进行注册的，在C盘host文件要做好映射
  server:
    #关闭默认保护机制，保证不可用的服务及时剔除（默认是CAP中的AP，即高可用和分区容错）
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000