server:
  port: 80


spring:
  application:
    name: cloud-order-openfeign-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#     单机版
      defaultZone: http://eureka8761.com:8761/eureka/
#      集群版
#      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/
  instance:
      instance-id: order80
      prefer-ip-address: true


#openfeign集成了ribbon 默认连接和读取时间为1S，特殊情况在这里设置
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试


#开启hystrix
feign:
  hystrix:
    enabled: true


#设置hystrix的超时访问时间，公式是(1+MaxAutoRetries+MaxAutoRetriesNextServer)*ReadTimeout,详情见github
#并不是像上面说的那样，可能环境不同吧，github上保留作参考吧！！！！
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3100


#feign以什么日志级别监控哪些接口
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignHystrixService: debug





