server:
  port: 6002

spring:
  application:
    name: cloud-alibaba-nacos-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080    #sentinel databoard 地址
        port: 8719                   #默认端口号，假如被占用自动+1直到找到未占用的为止
        datasource:                  #sentinel中的流控规则将要持久化到nacos中
          ds1:
            nacos:
              server-addr: localhost:8848
              dataId: cloud-alibaba-nacos-sentinel-service
              group: DEFAULT_GROUP
              data-type: json
              rule-type: flow
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://192.168.6.101:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities

#增加nacos的管理点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#  激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
