server:
  port: 8762


eureka:
  instance:
    hostname: eureka8762.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是服务中心，主要职责是维护服务，不用去检索服务
    service-url: #与eureka交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka8761.com:8761/eureka/  #服务器相互注册是根据域名进行注册的，在C盘host文件要做好映射
